//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace SBAIMS.App_Code {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("Invoice")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class Invoice : global::System.Data.DataSet {
        
        private USP_GETINVOICEDataTable tableUSP_GETINVOICE;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public Invoice() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected Invoice(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["USP_GETINVOICE"] != null)) {
                    base.Tables.Add(new USP_GETINVOICEDataTable(ds.Tables["USP_GETINVOICE"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public USP_GETINVOICEDataTable USP_GETINVOICE {
            get {
                return this.tableUSP_GETINVOICE;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            Invoice cln = ((Invoice)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["USP_GETINVOICE"] != null)) {
                    base.Tables.Add(new USP_GETINVOICEDataTable(ds.Tables["USP_GETINVOICE"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableUSP_GETINVOICE = ((USP_GETINVOICEDataTable)(base.Tables["USP_GETINVOICE"]));
            if ((initTable == true)) {
                if ((this.tableUSP_GETINVOICE != null)) {
                    this.tableUSP_GETINVOICE.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "Invoice";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/Invoice.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableUSP_GETINVOICE = new USP_GETINVOICEDataTable();
            base.Tables.Add(this.tableUSP_GETINVOICE);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeUSP_GETINVOICE() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            Invoice ds = new Invoice();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void USP_GETINVOICERowChangeEventHandler(object sender, USP_GETINVOICERowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class USP_GETINVOICEDataTable : global::System.Data.TypedTableBase<USP_GETINVOICERow> {
            
            private global::System.Data.DataColumn columnT001_INVOICEOD;
            
            private global::System.Data.DataColumn columnC_Id;
            
            private global::System.Data.DataColumn columnT001_DATE;
            
            private global::System.Data.DataColumn columnT001_TOTALRS;
            
            private global::System.Data.DataColumn columnT001_DISCOUNT;
            
            private global::System.Data.DataColumn columnT001_TAX;
            
            private global::System.Data.DataColumn columnT001_NETRS;
            
            private global::System.Data.DataColumn columnT001_NOTE;
            
            private global::System.Data.DataColumn columnT002_INVOICEBOOKID;
            
            private global::System.Data.DataColumn columnB_Id;
            
            private global::System.Data.DataColumn columnT002_QTY;
            
            private global::System.Data.DataColumn columnT002_TOTALRS;
            
            private global::System.Data.DataColumn columnC_Name;
            
            private global::System.Data.DataColumn columnC_City;
            
            private global::System.Data.DataColumn columnC_Contact;
            
            private global::System.Data.DataColumn columnB_Title;
            
            private global::System.Data.DataColumn columnB_Author;
            
            private global::System.Data.DataColumn columnB_Quantity;
            
            private global::System.Data.DataColumn columnB_Price;
            
            private global::System.Data.DataColumn columnB_Commission;
            
            private global::System.Data.DataColumn columnB_Shelf;
            
            private global::System.Data.DataColumn columnB_Genre;
            
            private global::System.Data.DataColumn columnB_Binding;
            
            private global::System.Data.DataColumn columnB_Pages;
            
            private global::System.Data.DataColumn columnImported;
            
            private global::System.Data.DataColumn columnP_Id;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public USP_GETINVOICEDataTable() {
                this.TableName = "USP_GETINVOICE";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal USP_GETINVOICEDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected USP_GETINVOICEDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn T001_INVOICEODColumn {
                get {
                    return this.columnT001_INVOICEOD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn C_IdColumn {
                get {
                    return this.columnC_Id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn T001_DATEColumn {
                get {
                    return this.columnT001_DATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn T001_TOTALRSColumn {
                get {
                    return this.columnT001_TOTALRS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn T001_DISCOUNTColumn {
                get {
                    return this.columnT001_DISCOUNT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn T001_TAXColumn {
                get {
                    return this.columnT001_TAX;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn T001_NETRSColumn {
                get {
                    return this.columnT001_NETRS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn T001_NOTEColumn {
                get {
                    return this.columnT001_NOTE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn T002_INVOICEBOOKIDColumn {
                get {
                    return this.columnT002_INVOICEBOOKID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn B_IdColumn {
                get {
                    return this.columnB_Id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn T002_QTYColumn {
                get {
                    return this.columnT002_QTY;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn T002_TOTALRSColumn {
                get {
                    return this.columnT002_TOTALRS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn C_NameColumn {
                get {
                    return this.columnC_Name;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn C_CityColumn {
                get {
                    return this.columnC_City;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn C_ContactColumn {
                get {
                    return this.columnC_Contact;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn B_TitleColumn {
                get {
                    return this.columnB_Title;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn B_AuthorColumn {
                get {
                    return this.columnB_Author;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn B_QuantityColumn {
                get {
                    return this.columnB_Quantity;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn B_PriceColumn {
                get {
                    return this.columnB_Price;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn B_CommissionColumn {
                get {
                    return this.columnB_Commission;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn B_ShelfColumn {
                get {
                    return this.columnB_Shelf;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn B_GenreColumn {
                get {
                    return this.columnB_Genre;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn B_BindingColumn {
                get {
                    return this.columnB_Binding;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn B_PagesColumn {
                get {
                    return this.columnB_Pages;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ImportedColumn {
                get {
                    return this.columnImported;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn P_IdColumn {
                get {
                    return this.columnP_Id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public USP_GETINVOICERow this[int index] {
                get {
                    return ((USP_GETINVOICERow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event USP_GETINVOICERowChangeEventHandler USP_GETINVOICERowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event USP_GETINVOICERowChangeEventHandler USP_GETINVOICERowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event USP_GETINVOICERowChangeEventHandler USP_GETINVOICERowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event USP_GETINVOICERowChangeEventHandler USP_GETINVOICERowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddUSP_GETINVOICERow(USP_GETINVOICERow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public USP_GETINVOICERow AddUSP_GETINVOICERow(
                        int C_Id, 
                        System.DateTime T001_DATE, 
                        decimal T001_TOTALRS, 
                        decimal T001_DISCOUNT, 
                        decimal T001_TAX, 
                        decimal T001_NETRS, 
                        string T001_NOTE, 
                        int B_Id, 
                        int T002_QTY, 
                        decimal T002_TOTALRS, 
                        string C_Name, 
                        string C_City, 
                        int C_Contact, 
                        string B_Title, 
                        string B_Author, 
                        string B_Quantity, 
                        int B_Price, 
                        int B_Commission, 
                        string B_Shelf, 
                        string B_Genre, 
                        string B_Binding, 
                        int B_Pages, 
                        string Imported, 
                        int P_Id) {
                USP_GETINVOICERow rowUSP_GETINVOICERow = ((USP_GETINVOICERow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        null,
                        C_Id,
                        T001_DATE,
                        T001_TOTALRS,
                        T001_DISCOUNT,
                        T001_TAX,
                        T001_NETRS,
                        T001_NOTE,
                        null,
                        B_Id,
                        T002_QTY,
                        T002_TOTALRS,
                        C_Name,
                        C_City,
                        C_Contact,
                        B_Title,
                        B_Author,
                        B_Quantity,
                        B_Price,
                        B_Commission,
                        B_Shelf,
                        B_Genre,
                        B_Binding,
                        B_Pages,
                        Imported,
                        P_Id};
                rowUSP_GETINVOICERow.ItemArray = columnValuesArray;
                this.Rows.Add(rowUSP_GETINVOICERow);
                return rowUSP_GETINVOICERow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                USP_GETINVOICEDataTable cln = ((USP_GETINVOICEDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new USP_GETINVOICEDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnT001_INVOICEOD = base.Columns["T001_INVOICEOD"];
                this.columnC_Id = base.Columns["C_Id"];
                this.columnT001_DATE = base.Columns["T001_DATE"];
                this.columnT001_TOTALRS = base.Columns["T001_TOTALRS"];
                this.columnT001_DISCOUNT = base.Columns["T001_DISCOUNT"];
                this.columnT001_TAX = base.Columns["T001_TAX"];
                this.columnT001_NETRS = base.Columns["T001_NETRS"];
                this.columnT001_NOTE = base.Columns["T001_NOTE"];
                this.columnT002_INVOICEBOOKID = base.Columns["T002_INVOICEBOOKID"];
                this.columnB_Id = base.Columns["B_Id"];
                this.columnT002_QTY = base.Columns["T002_QTY"];
                this.columnT002_TOTALRS = base.Columns["T002_TOTALRS"];
                this.columnC_Name = base.Columns["C_Name"];
                this.columnC_City = base.Columns["C_City"];
                this.columnC_Contact = base.Columns["C_Contact"];
                this.columnB_Title = base.Columns["B_Title"];
                this.columnB_Author = base.Columns["B_Author"];
                this.columnB_Quantity = base.Columns["B_Quantity"];
                this.columnB_Price = base.Columns["B_Price"];
                this.columnB_Commission = base.Columns["B_Commission"];
                this.columnB_Shelf = base.Columns["B_Shelf"];
                this.columnB_Genre = base.Columns["B_Genre"];
                this.columnB_Binding = base.Columns["B_Binding"];
                this.columnB_Pages = base.Columns["B_Pages"];
                this.columnImported = base.Columns["Imported"];
                this.columnP_Id = base.Columns["P_Id"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnT001_INVOICEOD = new global::System.Data.DataColumn("T001_INVOICEOD", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnT001_INVOICEOD);
                this.columnC_Id = new global::System.Data.DataColumn("C_Id", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnC_Id);
                this.columnT001_DATE = new global::System.Data.DataColumn("T001_DATE", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnT001_DATE);
                this.columnT001_TOTALRS = new global::System.Data.DataColumn("T001_TOTALRS", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnT001_TOTALRS);
                this.columnT001_DISCOUNT = new global::System.Data.DataColumn("T001_DISCOUNT", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnT001_DISCOUNT);
                this.columnT001_TAX = new global::System.Data.DataColumn("T001_TAX", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnT001_TAX);
                this.columnT001_NETRS = new global::System.Data.DataColumn("T001_NETRS", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnT001_NETRS);
                this.columnT001_NOTE = new global::System.Data.DataColumn("T001_NOTE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnT001_NOTE);
                this.columnT002_INVOICEBOOKID = new global::System.Data.DataColumn("T002_INVOICEBOOKID", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnT002_INVOICEBOOKID);
                this.columnB_Id = new global::System.Data.DataColumn("B_Id", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnB_Id);
                this.columnT002_QTY = new global::System.Data.DataColumn("T002_QTY", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnT002_QTY);
                this.columnT002_TOTALRS = new global::System.Data.DataColumn("T002_TOTALRS", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnT002_TOTALRS);
                this.columnC_Name = new global::System.Data.DataColumn("C_Name", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnC_Name);
                this.columnC_City = new global::System.Data.DataColumn("C_City", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnC_City);
                this.columnC_Contact = new global::System.Data.DataColumn("C_Contact", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnC_Contact);
                this.columnB_Title = new global::System.Data.DataColumn("B_Title", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnB_Title);
                this.columnB_Author = new global::System.Data.DataColumn("B_Author", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnB_Author);
                this.columnB_Quantity = new global::System.Data.DataColumn("B_Quantity", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnB_Quantity);
                this.columnB_Price = new global::System.Data.DataColumn("B_Price", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnB_Price);
                this.columnB_Commission = new global::System.Data.DataColumn("B_Commission", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnB_Commission);
                this.columnB_Shelf = new global::System.Data.DataColumn("B_Shelf", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnB_Shelf);
                this.columnB_Genre = new global::System.Data.DataColumn("B_Genre", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnB_Genre);
                this.columnB_Binding = new global::System.Data.DataColumn("B_Binding", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnB_Binding);
                this.columnB_Pages = new global::System.Data.DataColumn("B_Pages", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnB_Pages);
                this.columnImported = new global::System.Data.DataColumn("Imported", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnImported);
                this.columnP_Id = new global::System.Data.DataColumn("P_Id", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnP_Id);
                this.columnT001_INVOICEOD.AutoIncrement = true;
                this.columnT001_INVOICEOD.AllowDBNull = false;
                this.columnT001_INVOICEOD.ReadOnly = true;
                this.columnC_Id.AllowDBNull = false;
                this.columnT001_DATE.AllowDBNull = false;
                this.columnT001_TOTALRS.AllowDBNull = false;
                this.columnT001_NETRS.AllowDBNull = false;
                this.columnT001_NOTE.MaxLength = 150;
                this.columnT002_INVOICEBOOKID.AutoIncrement = true;
                this.columnT002_INVOICEBOOKID.AllowDBNull = false;
                this.columnT002_INVOICEBOOKID.ReadOnly = true;
                this.columnB_Id.AllowDBNull = false;
                this.columnT002_QTY.AllowDBNull = false;
                this.columnT002_TOTALRS.AllowDBNull = false;
                this.columnC_Name.AllowDBNull = false;
                this.columnC_Name.MaxLength = 2147483647;
                this.columnC_City.MaxLength = 30;
                this.columnB_Title.AllowDBNull = false;
                this.columnB_Title.MaxLength = 2147483647;
                this.columnB_Author.MaxLength = 2147483647;
                this.columnB_Quantity.AllowDBNull = false;
                this.columnB_Quantity.MaxLength = 2147483647;
                this.columnB_Price.AllowDBNull = false;
                this.columnB_Commission.AllowDBNull = false;
                this.columnB_Shelf.MaxLength = 2147483647;
                this.columnB_Genre.AllowDBNull = false;
                this.columnB_Genre.MaxLength = 2147483647;
                this.columnB_Binding.MaxLength = 2147483647;
                this.columnImported.MaxLength = 10;
                this.columnP_Id.AllowDBNull = false;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public USP_GETINVOICERow NewUSP_GETINVOICERow() {
                return ((USP_GETINVOICERow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new USP_GETINVOICERow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(USP_GETINVOICERow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.USP_GETINVOICERowChanged != null)) {
                    this.USP_GETINVOICERowChanged(this, new USP_GETINVOICERowChangeEvent(((USP_GETINVOICERow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.USP_GETINVOICERowChanging != null)) {
                    this.USP_GETINVOICERowChanging(this, new USP_GETINVOICERowChangeEvent(((USP_GETINVOICERow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.USP_GETINVOICERowDeleted != null)) {
                    this.USP_GETINVOICERowDeleted(this, new USP_GETINVOICERowChangeEvent(((USP_GETINVOICERow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.USP_GETINVOICERowDeleting != null)) {
                    this.USP_GETINVOICERowDeleting(this, new USP_GETINVOICERowChangeEvent(((USP_GETINVOICERow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveUSP_GETINVOICERow(USP_GETINVOICERow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                Invoice ds = new Invoice();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "USP_GETINVOICEDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class USP_GETINVOICERow : global::System.Data.DataRow {
            
            private USP_GETINVOICEDataTable tableUSP_GETINVOICE;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal USP_GETINVOICERow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableUSP_GETINVOICE = ((USP_GETINVOICEDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int T001_INVOICEOD {
                get {
                    return ((int)(this[this.tableUSP_GETINVOICE.T001_INVOICEODColumn]));
                }
                set {
                    this[this.tableUSP_GETINVOICE.T001_INVOICEODColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int C_Id {
                get {
                    return ((int)(this[this.tableUSP_GETINVOICE.C_IdColumn]));
                }
                set {
                    this[this.tableUSP_GETINVOICE.C_IdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime T001_DATE {
                get {
                    return ((global::System.DateTime)(this[this.tableUSP_GETINVOICE.T001_DATEColumn]));
                }
                set {
                    this[this.tableUSP_GETINVOICE.T001_DATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal T001_TOTALRS {
                get {
                    return ((decimal)(this[this.tableUSP_GETINVOICE.T001_TOTALRSColumn]));
                }
                set {
                    this[this.tableUSP_GETINVOICE.T001_TOTALRSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal T001_DISCOUNT {
                get {
                    try {
                        return ((decimal)(this[this.tableUSP_GETINVOICE.T001_DISCOUNTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'T001_DISCOUNT\' in table \'USP_GETINVOICE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUSP_GETINVOICE.T001_DISCOUNTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal T001_TAX {
                get {
                    try {
                        return ((decimal)(this[this.tableUSP_GETINVOICE.T001_TAXColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'T001_TAX\' in table \'USP_GETINVOICE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUSP_GETINVOICE.T001_TAXColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal T001_NETRS {
                get {
                    return ((decimal)(this[this.tableUSP_GETINVOICE.T001_NETRSColumn]));
                }
                set {
                    this[this.tableUSP_GETINVOICE.T001_NETRSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string T001_NOTE {
                get {
                    try {
                        return ((string)(this[this.tableUSP_GETINVOICE.T001_NOTEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'T001_NOTE\' in table \'USP_GETINVOICE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUSP_GETINVOICE.T001_NOTEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int T002_INVOICEBOOKID {
                get {
                    return ((int)(this[this.tableUSP_GETINVOICE.T002_INVOICEBOOKIDColumn]));
                }
                set {
                    this[this.tableUSP_GETINVOICE.T002_INVOICEBOOKIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int B_Id {
                get {
                    return ((int)(this[this.tableUSP_GETINVOICE.B_IdColumn]));
                }
                set {
                    this[this.tableUSP_GETINVOICE.B_IdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int T002_QTY {
                get {
                    return ((int)(this[this.tableUSP_GETINVOICE.T002_QTYColumn]));
                }
                set {
                    this[this.tableUSP_GETINVOICE.T002_QTYColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal T002_TOTALRS {
                get {
                    return ((decimal)(this[this.tableUSP_GETINVOICE.T002_TOTALRSColumn]));
                }
                set {
                    this[this.tableUSP_GETINVOICE.T002_TOTALRSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string C_Name {
                get {
                    return ((string)(this[this.tableUSP_GETINVOICE.C_NameColumn]));
                }
                set {
                    this[this.tableUSP_GETINVOICE.C_NameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string C_City {
                get {
                    try {
                        return ((string)(this[this.tableUSP_GETINVOICE.C_CityColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'C_City\' in table \'USP_GETINVOICE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUSP_GETINVOICE.C_CityColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int C_Contact {
                get {
                    try {
                        return ((int)(this[this.tableUSP_GETINVOICE.C_ContactColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'C_Contact\' in table \'USP_GETINVOICE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUSP_GETINVOICE.C_ContactColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string B_Title {
                get {
                    return ((string)(this[this.tableUSP_GETINVOICE.B_TitleColumn]));
                }
                set {
                    this[this.tableUSP_GETINVOICE.B_TitleColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string B_Author {
                get {
                    try {
                        return ((string)(this[this.tableUSP_GETINVOICE.B_AuthorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'B_Author\' in table \'USP_GETINVOICE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUSP_GETINVOICE.B_AuthorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string B_Quantity {
                get {
                    return ((string)(this[this.tableUSP_GETINVOICE.B_QuantityColumn]));
                }
                set {
                    this[this.tableUSP_GETINVOICE.B_QuantityColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int B_Price {
                get {
                    return ((int)(this[this.tableUSP_GETINVOICE.B_PriceColumn]));
                }
                set {
                    this[this.tableUSP_GETINVOICE.B_PriceColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int B_Commission {
                get {
                    return ((int)(this[this.tableUSP_GETINVOICE.B_CommissionColumn]));
                }
                set {
                    this[this.tableUSP_GETINVOICE.B_CommissionColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string B_Shelf {
                get {
                    try {
                        return ((string)(this[this.tableUSP_GETINVOICE.B_ShelfColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'B_Shelf\' in table \'USP_GETINVOICE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUSP_GETINVOICE.B_ShelfColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string B_Genre {
                get {
                    return ((string)(this[this.tableUSP_GETINVOICE.B_GenreColumn]));
                }
                set {
                    this[this.tableUSP_GETINVOICE.B_GenreColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string B_Binding {
                get {
                    try {
                        return ((string)(this[this.tableUSP_GETINVOICE.B_BindingColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'B_Binding\' in table \'USP_GETINVOICE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUSP_GETINVOICE.B_BindingColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int B_Pages {
                get {
                    try {
                        return ((int)(this[this.tableUSP_GETINVOICE.B_PagesColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'B_Pages\' in table \'USP_GETINVOICE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUSP_GETINVOICE.B_PagesColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Imported {
                get {
                    try {
                        return ((string)(this[this.tableUSP_GETINVOICE.ImportedColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Imported\' in table \'USP_GETINVOICE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUSP_GETINVOICE.ImportedColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int P_Id {
                get {
                    return ((int)(this[this.tableUSP_GETINVOICE.P_IdColumn]));
                }
                set {
                    this[this.tableUSP_GETINVOICE.P_IdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsT001_DISCOUNTNull() {
                return this.IsNull(this.tableUSP_GETINVOICE.T001_DISCOUNTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetT001_DISCOUNTNull() {
                this[this.tableUSP_GETINVOICE.T001_DISCOUNTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsT001_TAXNull() {
                return this.IsNull(this.tableUSP_GETINVOICE.T001_TAXColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetT001_TAXNull() {
                this[this.tableUSP_GETINVOICE.T001_TAXColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsT001_NOTENull() {
                return this.IsNull(this.tableUSP_GETINVOICE.T001_NOTEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetT001_NOTENull() {
                this[this.tableUSP_GETINVOICE.T001_NOTEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsC_CityNull() {
                return this.IsNull(this.tableUSP_GETINVOICE.C_CityColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetC_CityNull() {
                this[this.tableUSP_GETINVOICE.C_CityColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsC_ContactNull() {
                return this.IsNull(this.tableUSP_GETINVOICE.C_ContactColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetC_ContactNull() {
                this[this.tableUSP_GETINVOICE.C_ContactColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsB_AuthorNull() {
                return this.IsNull(this.tableUSP_GETINVOICE.B_AuthorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetB_AuthorNull() {
                this[this.tableUSP_GETINVOICE.B_AuthorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsB_ShelfNull() {
                return this.IsNull(this.tableUSP_GETINVOICE.B_ShelfColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetB_ShelfNull() {
                this[this.tableUSP_GETINVOICE.B_ShelfColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsB_BindingNull() {
                return this.IsNull(this.tableUSP_GETINVOICE.B_BindingColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetB_BindingNull() {
                this[this.tableUSP_GETINVOICE.B_BindingColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsB_PagesNull() {
                return this.IsNull(this.tableUSP_GETINVOICE.B_PagesColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetB_PagesNull() {
                this[this.tableUSP_GETINVOICE.B_PagesColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsImportedNull() {
                return this.IsNull(this.tableUSP_GETINVOICE.ImportedColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetImportedNull() {
                this[this.tableUSP_GETINVOICE.ImportedColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class USP_GETINVOICERowChangeEvent : global::System.EventArgs {
            
            private USP_GETINVOICERow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public USP_GETINVOICERowChangeEvent(USP_GETINVOICERow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public USP_GETINVOICERow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
namespace SBAIMS.App_Code.InvoiceTableAdapters {
    
    
    /// <summary>
    ///Represents the connection and commands used to retrieve and save data.
    ///</summary>
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.ComponentModel.DataObjectAttribute(true)]
    [global::System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterDesigner, Microsoft.VSDesigner" +
        ", Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
    public partial class USP_GETINVOICETableAdapter : global::System.ComponentModel.Component {
        
        private global::System.Data.SqlClient.SqlDataAdapter _adapter;
        
        private global::System.Data.SqlClient.SqlConnection _connection;
        
        private global::System.Data.SqlClient.SqlCommand[] _commandCollection;
        
        private bool _clearBeforeFill;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public USP_GETINVOICETableAdapter() {
            this.ClearBeforeFill = true;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private global::System.Data.SqlClient.SqlDataAdapter Adapter {
            get {
                if ((this._adapter == null)) {
                    this.InitAdapter();
                }
                return this._adapter;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal global::System.Data.SqlClient.SqlConnection Connection {
            get {
                if ((this._connection == null)) {
                    this.InitConnection();
                }
                return this._connection;
            }
            set {
                this._connection = value;
                if ((this.Adapter.InsertCommand != null)) {
                    this.Adapter.InsertCommand.Connection = value;
                }
                if ((this.Adapter.DeleteCommand != null)) {
                    this.Adapter.DeleteCommand.Connection = value;
                }
                if ((this.Adapter.UpdateCommand != null)) {
                    this.Adapter.UpdateCommand.Connection = value;
                }
                for (int i = 0; (i < this.CommandCollection.Length); i = (i + 1)) {
                    if ((this.CommandCollection[i] != null)) {
                        ((global::System.Data.SqlClient.SqlCommand)(this.CommandCollection[i])).Connection = value;
                    }
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected global::System.Data.SqlClient.SqlCommand[] CommandCollection {
            get {
                if ((this._commandCollection == null)) {
                    this.InitCommandCollection();
                }
                return this._commandCollection;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public bool ClearBeforeFill {
            get {
                return this._clearBeforeFill;
            }
            set {
                this._clearBeforeFill = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitAdapter() {
            this._adapter = new global::System.Data.SqlClient.SqlDataAdapter();
            global::System.Data.Common.DataTableMapping tableMapping = new global::System.Data.Common.DataTableMapping();
            tableMapping.SourceTable = "Table";
            tableMapping.DataSetTable = "USP_GETINVOICE";
            tableMapping.ColumnMappings.Add("T001_INVOICEOD", "T001_INVOICEOD");
            tableMapping.ColumnMappings.Add("C_Id", "C_Id");
            tableMapping.ColumnMappings.Add("T001_DATE", "T001_DATE");
            tableMapping.ColumnMappings.Add("T001_TOTALRS", "T001_TOTALRS");
            tableMapping.ColumnMappings.Add("T001_DISCOUNT", "T001_DISCOUNT");
            tableMapping.ColumnMappings.Add("T001_TAX", "T001_TAX");
            tableMapping.ColumnMappings.Add("T001_NETRS", "T001_NETRS");
            tableMapping.ColumnMappings.Add("T001_NOTE", "T001_NOTE");
            tableMapping.ColumnMappings.Add("T002_INVOICEBOOKID", "T002_INVOICEBOOKID");
            tableMapping.ColumnMappings.Add("B_Id", "B_Id");
            tableMapping.ColumnMappings.Add("T002_QTY", "T002_QTY");
            tableMapping.ColumnMappings.Add("T002_TOTALRS", "T002_TOTALRS");
            tableMapping.ColumnMappings.Add("C_Name", "C_Name");
            tableMapping.ColumnMappings.Add("C_City", "C_City");
            tableMapping.ColumnMappings.Add("C_Contact", "C_Contact");
            tableMapping.ColumnMappings.Add("B_Title", "B_Title");
            tableMapping.ColumnMappings.Add("B_Author", "B_Author");
            tableMapping.ColumnMappings.Add("B_Quantity", "B_Quantity");
            tableMapping.ColumnMappings.Add("B_Price", "B_Price");
            tableMapping.ColumnMappings.Add("B_Commission", "B_Commission");
            tableMapping.ColumnMappings.Add("B_Shelf", "B_Shelf");
            tableMapping.ColumnMappings.Add("B_Genre", "B_Genre");
            tableMapping.ColumnMappings.Add("B_Binding", "B_Binding");
            tableMapping.ColumnMappings.Add("B_Pages", "B_Pages");
            tableMapping.ColumnMappings.Add("Imported", "Imported");
            tableMapping.ColumnMappings.Add("P_Id", "P_Id");
            this._adapter.TableMappings.Add(tableMapping);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitConnection() {
            this._connection = new global::System.Data.SqlClient.SqlConnection();
            this._connection.ConnectionString = System.Configuration.ConfigurationManager.ConnectionStrings["SBAIMSConnectionString1"].ConnectionString;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitCommandCollection() {
            this._commandCollection = new global::System.Data.SqlClient.SqlCommand[1];
            this._commandCollection[0] = new global::System.Data.SqlClient.SqlCommand();
            this._commandCollection[0].Connection = this.Connection;
            this._commandCollection[0].CommandText = "dbo.USP_GETINVOICE";
            this._commandCollection[0].CommandType = global::System.Data.CommandType.StoredProcedure;
            this._commandCollection[0].Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@RETURN_VALUE", global::System.Data.SqlDbType.Int, 4, global::System.Data.ParameterDirection.ReturnValue, 10, 0, null, global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._commandCollection[0].Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@T001_INVOICEOD", global::System.Data.SqlDbType.VarChar, 2147483647, global::System.Data.ParameterDirection.Input, 0, 0, null, global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._commandCollection[0].Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@C_Id", global::System.Data.SqlDbType.VarChar, 2147483647, global::System.Data.ParameterDirection.Input, 0, 0, null, global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._commandCollection[0].Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@T001_DATE", global::System.Data.SqlDbType.Date, 3, global::System.Data.ParameterDirection.Input, 10, 0, null, global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Fill, true)]
        public virtual int Fill(Invoice.USP_GETINVOICEDataTable dataTable, string T001_INVOICEOD, string C_Id, global::System.Nullable<global::System.DateTime> T001_DATE) {
            this.Adapter.SelectCommand = this.CommandCollection[0];
            if ((T001_INVOICEOD == null)) {
                this.Adapter.SelectCommand.Parameters[1].Value = global::System.DBNull.Value;
            }
            else {
                this.Adapter.SelectCommand.Parameters[1].Value = ((string)(T001_INVOICEOD));
            }
            if ((C_Id == null)) {
                this.Adapter.SelectCommand.Parameters[2].Value = global::System.DBNull.Value;
            }
            else {
                this.Adapter.SelectCommand.Parameters[2].Value = ((string)(C_Id));
            }
            if ((T001_DATE.HasValue == true)) {
                this.Adapter.SelectCommand.Parameters[3].Value = ((System.DateTime)(T001_DATE.Value));
            }
            else {
                this.Adapter.SelectCommand.Parameters[3].Value = global::System.DBNull.Value;
            }
            if ((this.ClearBeforeFill == true)) {
                dataTable.Clear();
            }
            int returnValue = this.Adapter.Fill(dataTable);
            return returnValue;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Select, true)]
        public virtual Invoice.USP_GETINVOICEDataTable GetData(string T001_INVOICEOD, string C_Id, global::System.Nullable<global::System.DateTime> T001_DATE) {
            this.Adapter.SelectCommand = this.CommandCollection[0];
            if ((T001_INVOICEOD == null)) {
                this.Adapter.SelectCommand.Parameters[1].Value = global::System.DBNull.Value;
            }
            else {
                this.Adapter.SelectCommand.Parameters[1].Value = ((string)(T001_INVOICEOD));
            }
            if ((C_Id == null)) {
                this.Adapter.SelectCommand.Parameters[2].Value = global::System.DBNull.Value;
            }
            else {
                this.Adapter.SelectCommand.Parameters[2].Value = ((string)(C_Id));
            }
            if ((T001_DATE.HasValue == true)) {
                this.Adapter.SelectCommand.Parameters[3].Value = ((System.DateTime)(T001_DATE.Value));
            }
            else {
                this.Adapter.SelectCommand.Parameters[3].Value = global::System.DBNull.Value;
            }
            Invoice.USP_GETINVOICEDataTable dataTable = new Invoice.USP_GETINVOICEDataTable();
            this.Adapter.Fill(dataTable);
            return dataTable;
        }
    }
}

#pragma warning restore 1591